;DISPLAY_LOOKUP SEGMENT CODE

;RSEG DISPLAY_LOOKUP
;			0	  1     2     3     4     5     6     7     8     9     A     B     C     D     E     F     0 A   1 O   2 n   3 X   4 P   5 M   6 L   7 R
;TABLE:   DB 0C0H, 0F9H, 0A4H, 0B0H, 099H, 092H, 082H, 0F8H, 080H, 090H, 038H, 080H, 0C6H, 0C0H, 086H, 08EH, 088H, 0C0H, 0ABH, 089H, 08CH, 0C8H, 0C7H, 084H
;																											+16    

DISPLAY_LOOKUP SEGMENT CODE
	
RSEG DISPLAY_LOOKUP
;			0	  1     2     3     4     5     6     7     8     9     L     O      b     F   
TABLE:   DB 0C0H, 0F9H, 0A4H, 0B0H, 099H, 092H, 082H, 0F8H, 080H, 090H, 0C7H, 0C0H, 083H, 08EH